## Plink script for CVD - Loci in LD with QSNPs

plink --bfile ./reference_files/g1000_eur/g1000_eur \
--clump ./0_clumping/cvd_clump/cvd_QSNP_Pfile.tsv \
--clump-p1 5e-8 \
--clump-p2 5e-4 \
--clump-r2 0.10 \
--clump-kb 1000 \
--out GSEM_cvd_clump

p1 = genome-wide significance 
p2 = secondary significant threshold for clumped SNPs
r2 = LD threshold for clumping
kb = distance around index SNP for clumping

## Plink script for Metab - Loci in LD with QSNPs

plink --bfile ./reference_files/g1000_eur/g1000_eur \
--clump ./0_clumping/metab_clump/metab_QSNP_Pfile.tsv \
--clump-p1 5e-8 \
--clump-p2 5e-4 \
--clump-r2 0.10 \
--clump-kb 1000 \
--out GSEM_metab_GCF_common_clump

p1 = genome-wide significance 
p2 = secondary significant threshold for clumped SNPs
r2 = LD threshold for clumping
kb = distance around index SNP for clumping

## Plink script for Gastro - Loci in LD with QSNPs

plink --bfile ./reference_files/g1000_eur/g1000_eur \
--clump ./0_clumping/gastro_clump/gastro_QSNP_Pfile.tsv \
--clump-p1 5e-8 \
--clump-p2 5e-4 \
--clump-r2 0.10 \
--clump-kb 1000 \
--out GSEM_gastro_common_clump

p1 = genome-wide significance 
p2 = secondary significant threshold for clumped SNPs
r2 = LD threshold for clumping
kb = distance around index SNP for clumping

## Plink script for Immune - Loci in LD with QSNPs

plink --bfile ./reference_files/g1000_eur/g1000_eur \
--clump ./0_clumping/im_clump/im_QSNP_Pfile.tsv \
--clump-p1 5e-8 \
--clump-p2 5e-4 \
--clump-r2 0.10 \
--clump-kb 1000 \
--out GSEM_IM_common_clump

p1 = genome-wide significance 
p2 = secondary significant threshold for clumped SNPs
r2 = LD threshold for clumping
kb = distance around index SNP for clumping
