#!/bin/bash
#PBS -N gsamixer       
#PBS -l walltime=6:00:00 
#PBS -l select=1:ncpus=8:mem=36GB  

module load singularity/3.7.1 

cd ./MIXER_GSA

FILE=($(awk -v var=$PBS_ARRAY_INDEX 'NR==var {print $1}' sumstats.txt))

# custom path & settings
export THREADS=8
export MIXER_SIF=./singularity/gsa-mixer-2.1.1.sif
export SUMSTATS_FOLDER=./MIXER_GSA/splitsumstats
export SUMSTATS_FILE=${FILE}
export OUT_FOLDER=./MIXER_GSA/2_GO
export BASELINE_FOLDER=./MIXER_GSA/1_baseline

# select which analyses to trigger
export DO_MIXER=true
export DO_MAGMA=true

# standard GSA-MiXeR pipeline begins here 
export PYTHON="singularity exec --home /software/gsa-mixer/gsa-mixer-2.1.1:/home ${MIXER_SIF} python"
export MIXER_PY="$PYTHON /tools/mixer/precimed/mixer.py"
export MAGMA="singularity exec --home /software/gsa-mixer/gsa-mixer-2.1.1:/home ${MIXER_SIF} magma"

export MAGMA_BFILE=./MIXER_GSA/mixer/reference/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.merged
export MAGMA_GENE_LOC=./MIXER_GSA/mixer/reference/magma/magma-gene-annot_10mar2023.csv
export MAGMA_SET_ANNOT=/MIXER_GSA/mixer/reference/magma/magma-geneset-annot_10mar2023.csv

export EXTRA_FLAGS="--seed 1000 --exclude-ranges MHC --hardprune-r2 0.6 --threads ${THREADS}"

export REFERENCE_FOLDER=./MIXER_GSA/mixer/reference/magma
export BIM_FILE=./MIXER_GSA/mixer/reference/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim
export LOADLIB_FILE=./MIXER_GSA/mixer/reference/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bin
export ANNOT_FILE=./MIXER_GSA/mixer/reference/ldsc/1000G_EUR_Phase3_plink/baseline_v2.2_1000G.EUR.QC.@.annot.gz

if ${DO_MIXER}; then

# GSA-MiXeR analysis - enrichment model
${MIXER_PY} plsa --gsa-full \
        --trait1-file ${SUMSTATS_FOLDER}/${SUMSTATS_FILE}.chr@.sumstats.gz \
        --out ${OUT_FOLDER}/${SUMSTATS_FILE}_full \
        --bim-file ${BIM_FILE} --use-complete-tag-indices --loadlib-file ${LOADLIB_FILE} \
        --go-file ${REFERENCE_FOLDER}/gsa-mixer-gene-annot_10mar2023.csv \
        --go-file-test ${REFERENCE_FOLDER}/gsa-mixer-hybridLOO-annot_10mar2023.csv \
        --annot-file ${ANNOT_FILE} \
        --load-params-file ${BASELINE_FOLDER}/${SUMSTATS_FILE}_base.json \
        ${EXTRA_FLAGS}

fi


if ${DO_MAGMA}; then

cd ./15_MIXER_GSA

# MAGMA analysis - annotate snps to genes
$MAGMA --snp-loc ${MAGMA_BFILE}.bim \
       --gene-loc ${MAGMA_GENE_LOC} \
       --out ./2_GO/${FILE}_magma.step1 \
       --annotate window=10

# MAGMA analysis - compute gene-level p-values
$MAGMA --pval ./sumstats/${FILE}_clean.tsv snp-id=SNP pval=P ncol=N \
       --bfile ${MAGMA_BFILE} \
       --gene-annot ./2_GO/${FILE}_magma.step1.genes.annot \
       --out ./2_GO/${FILE}_magma.step2

# MAGMA analysis - compute geneset-level p-values
$MAGMA --gene-results ./2_GO/${FILE}_magma.step2.genes.raw \
       --set-annot ${MAGMA_SET_ANNOT} \
       --out ./2_GO/${FILE}_magma
fi