#!/bin/bash
#PBS -N gsamixer       
#PBS -l walltime=6:00:00 
#PBS -l select=1:ncpus=8:mem=36GB  

module load singularity/3.7.1 

cd ./MIXER_GSA

# custom path & settings
export THREADS=8
export MIXER_SIF=./singularity/gsa-mixer-2.1.1.sif
export SUMSTATS_FOLDER=./MIXER_GSA/splitsumstats
export SUMSTATS_FILE=${FILE}
export OUT_FOLDER=./MIXER_GSA/1_baseline

# standard GSA-MiXeR pipeline begins here 
export PYTHON="singularity exec --home /software/gsa-mixer/gsa-mixer-2.1.1:/home ${MIXER_SIF} python"
export MIXER_PY="$PYTHON /tools/mixer/precimed/mixer.py"
export EXTRA_FLAGS="--seed 1000 --exclude-ranges MHC --hardprune-r2 0.6 --threads ${THREADS}"

export REFERENCE_FOLDER=./MIXER_GSA/mixer/reference/magma
export BIM_FILE=./MIXER_GSA/mixer/reference/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim
export LOADLIB_FILE=./MIXER_GSA/mixer/reference/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bin
export ANNOT_FILE=./MIXER_GSA/mixer/reference/ldsc/1000G_EUR_Phase3_plink/baseline_v2.2_1000G.EUR.QC.@.annot.gz

# GSA-MiXeR analysis - baseline
${MIXER_PY} plsa --gsa-base \
        --trait1-file ${SUMSTATS_FOLDER}/MDD_Factor.chr@.sumstats.gz \
        --out ${OUT_FOLDER}/MDD_base \
        --bim-file ${BIM_FILE} --use-complete-tag-indices --loadlib-file ${LOADLIB_FILE} \
        --go-file ${REFERENCE_FOLDER}/gsa-mixer-baseline-annot_10mar2023.csv \
        --annot-file ${ANNOT_FILE} \
        ${EXTRA_FLAGS}